<a href="https://colab.research.google.com/github/GalynaDe/ML/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
vector = np.random.rand(10)
print(vector)
print(vector.reshape(-1, 1))


[0.54118749 0.24806281 0.18062174 0.22628503 0.360252   0.8225752
 0.81835618 0.05487722 0.26468894 0.40135876]
[[0.54118749]
 [0.24806281]
 [0.18062174]
 [0.22628503]
 [0.360252  ]
 [0.8225752 ]
 [0.81835618]
 [0.05487722]
 [0.26468894]
 [0.40135876]]


In [ ]:
print("Вектор:")
print(vector.reshape(-1, 1))
print("\nРозмір вектора:", vector.shape)

Вектор:
[[0.54118749]
 [0.24806281]
 [0.18062174]
 [0.22628503]
 [0.360252  ]
 [0.8225752 ]
 [0.81835618]
 [0.05487722]
 [0.26468894]
 [0.40135876]]

Розмір вектора: (10,)


In [ ]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print("\nМатриця:")
print(matrix)
print("\nРозмір матриці:", matrix.shape)


Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector_plus_10 = np.round(vector + 10, 2)
matrix_times_2 = matrix *2
vector_squared = np.square(vector)
print("Вектор з додаванням 10 і округленням до 2 знаків після коми:")
print(vector_plus_10.reshape(-1, 1))
print("\nМатриця, помножена на 2:")
print(matrix_times_2)
print("\nВектор, що містить квадрат кожного значення:")
print(vector_squared.reshape(-1, 1))

Вектор з додаванням 10 і округленням до 2 знаків після коми:
[[10.54]
 [10.25]
 [10.18]
 [10.23]
 [10.36]
 [10.82]
 [10.82]
 [10.05]
 [10.26]
 [10.4 ]]

Матриця, помножена на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]

Вектор, що містить квадрат кожного значення:
[[0.2928839 ]
 [0.06153516]
 [0.03262421]
 [0.05120491]
 [0.1297815 ]
 [0.67662996]
 [0.66970684]
 [0.00301151]
 [0.07006024]
 [0.16108885]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

1.

In [ ]:
result_matrix = np.dot(A, B)
print("Результуюча матриця:")
print(result_matrix)

Результуюча матриця:
[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


Для того щоб отримати матрицю розмірністю 2x2, потрібно змінити розміри вихідних матриць:

In [ ]:
A = np.array([[0.18, 0.53], [0.75, 0.47]])
B = np.array([[0.17, 0.58], [0.38, 0.11]])
result_matrix = np.dot(A, B)
print(result_matrix)

[[0.232  0.1627]
 [0.3061 0.4867]]


2.при множенні матриці result_matrix розміром 2x2 на вектор C розміром 2x1. Результуюча матриця буде мати розмір 2x1.

In [ ]:
result_matrix = np.dot(A, B)
result_vector = np.dot(result_matrix, C)
print("Результуючий вектор:")
print(result_vector)


Результуючий вектор:
[[0.1627]
 [0.4867]]


3.При множенні матриці result_matrix розміром 2x2 на матрицю D розміром 2x2 результуюча матриця буде мати розмір 2x2.

In [ ]:
final_result = np.dot(result_matrix, D)
print("Результуюча матриця:")
print(final_result)

Результуюча матриця:
[[0.1627 0.232 ]
 [0.4867 0.3061]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
transposed_matrix = np.transpose(result_matrix)
print("Транспонована матриця:")
print(transposed_matrix)

Транспонована матриця:
[[0.232  0.3061]
 [0.1627 0.4867]]


In [ ]:
vector = np.random.rand(10)
transposed_vector = vector.reshape(1, -1)
print("Транспонований вектор:")
print(transposed_vector)
print("\nФорма транспонованого вектора:", transposed_vector.shape)

Транспонований вектор:
[[0.81085178 0.29118046 0.94022156 0.23134679 0.61506845 0.03805719
  0.16199842 0.68312165 0.42457115 0.98036678]]

Форма транспонованого вектора: (1, 10)


Висновок: форма змінилася з (10,) на (1, 10), що означає, що вектор тепер представлений як рядок

In [ ]:
column_vector = np.expand_dims(vector, axis=1)
print("Початковий вектор:")
print(vector)
print("\nФорма початкового вектора:", vector.shape)
print("\nВектор після використання numpy.expand_dims:")
print(column_vector)
print("\nФорма вектора після використання numpy.expand_dims:", column_vector.shape)

Початковий вектор:
[0.81085178 0.29118046 0.94022156 0.23134679 0.61506845 0.03805719
 0.16199842 0.68312165 0.42457115 0.98036678]

Форма початкового вектора: (10,)

Вектор після використання numpy.expand_dims:
[[0.81085178]
 [0.29118046]
 [0.94022156]
 [0.23134679]
 [0.61506845]
 [0.03805719]
 [0.16199842]
 [0.68312165]
 [0.42457115]
 [0.98036678]]

Форма вектора після використання numpy.expand_dims: (10, 1)


In [ ]:
transposed_column_vector = column_vector.T
print("Транспонований column_vector:")
print(transposed_column_vector)
print("\nФорма транспонованого column_vector:", transposed_column_vector.shape)

Транспонований column_vector:
[[0.81085178 0.29118046 0.94022156 0.23134679 0.61506845 0.03805719
  0.16199842 0.68312165 0.42457115 0.98036678]]

Форма транспонованого column_vector: (1, 10)
